// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WasmExecutionInput {
    /// The input data for stdin (as a byte array).
    #[prost(bytes = "vec", tag = "1")]
    pub stdin: ::prost::alloc::vec::Vec<u8>,
    /// Arguments to be passed to the Wasm module.
    #[prost(string, repeated, tag = "2")]
    pub args: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Environment variables to be set for the Wasm module.
    #[prost(map = "string, string", tag = "3")]
    pub envs: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// Memory limit for the Wasm module in bytes.
    #[prost(uint64, tag = "4")]
    pub memory_limit: u64,
    /// Fuel limit for the Wasm module (used for controlling execution steps).
    #[prost(uint64, tag = "5")]
    pub fuel_limit: u64,
    /// The maximum size of the output buffer for stdout, in bytes.
    #[prost(uint64, tag = "6")]
    pub stdout_limit: u64,
    /// The maximum size of the output buffer for stderr, in bytes.
    #[prost(uint64, tag = "7")]
    pub stderr_limit: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WasmExecutionOutput {
    /// The output produced by the Wasm module's stdout.
    #[prost(bytes = "vec", tag = "1")]
    pub stdout: ::prost::alloc::vec::Vec<u8>,
    /// The output produced by the Wasm module's stderr.
    #[prost(bytes = "vec", tag = "2")]
    pub stderr: ::prost::alloc::vec::Vec<u8>,
    /// The amount of memory used during execution in bytes.
    #[prost(uint64, tag = "3")]
    pub memory_used: u64,
    /// The amount of fuel consumed during execution.
    #[prost(uint64, tag = "4")]
    pub fuel_consumed: u64,
    /// Whether the Wasm module ran successfully or not.
    #[prost(uint32, tag = "5")]
    pub status: u32,
    /// The hash of the bytes if requested.
    #[prost(uint64, tag = "6")]
    pub stdout_hash: u64,
    /// The hash of the token stream if requested.
    #[prost(uint64, tag = "7")]
    pub stdout_token_stream_hash: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WasmExecutionRequest {
    /// The Wasm binary to be executed (as a byte array).
    #[prost(bytes = "vec", repeated, tag = "1")]
    pub wasm_binary_arr: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(message, repeated, tag = "2")]
    pub inputs: ::prost::alloc::vec::Vec<WasmExecutionInput>,
    /// Preferred compression type for bytes.
    #[prost(enumeration = "CompressionType", tag = "9")]
    pub compression: i32,
    /// Option to return only the hash of the bytes and token stream hash.
    #[prost(bool, tag = "10")]
    pub return_hash_only: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WasmExecutionResponse {
    #[prost(message, repeated, tag = "1")]
    pub outputs: ::prost::alloc::vec::Vec<WasmExecutionOutput>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CompressionType {
    None = 0,
    Zstd = 2,
}
impl CompressionType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::None => "None",
            Self::Zstd => "Zstd",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "None" => Some(Self::None),
            "Zstd" => Some(Self::Zstd),
            _ => None,
        }
    }
}
/// Generated server implementations.
pub mod wasm_executor_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with WasmExecutorServer.
    #[async_trait]
    pub trait WasmExecutor: std::marker::Send + std::marker::Sync + 'static {
        /// Executes a Wasm module with the provided inputs and returns the results.
        async fn execute(
            &self,
            request: tonic::Request<super::WasmExecutionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::WasmExecutionResponse>,
            tonic::Status,
        >;
    }
    /// The service definition for executing Wasm modules.
    #[derive(Debug)]
    pub struct WasmExecutorServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> WasmExecutorServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for WasmExecutorServer<T>
    where
        T: WasmExecutor,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/wasm.WasmExecutor/Execute" => {
                    #[allow(non_camel_case_types)]
                    struct ExecuteSvc<T: WasmExecutor>(pub Arc<T>);
                    impl<
                        T: WasmExecutor,
                    > tonic::server::UnaryService<super::WasmExecutionRequest>
                    for ExecuteSvc<T> {
                        type Response = super::WasmExecutionResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::WasmExecutionRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as WasmExecutor>::execute(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ExecuteSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for WasmExecutorServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "wasm.WasmExecutor";
    impl<T> tonic::server::NamedService for WasmExecutorServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
