// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/r27153733/fastgozero/core/stores/builder"
	"github.com/r27153733/fastgozero/core/stores/sqlx"
	"github.com/r27153733/fastgozero/core/stringx"
)

var (
	judgeCaseFieldNames                  = builder.RawFieldNames(&JudgeCase{}, true)
	judgeCaseRows                        = strings.Join(judgeCaseFieldNames, ",")
	judgeCaseRowsExpectAutoSet           = strings.Join(stringx.Remove(judgeCaseFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	judgeCaseRowsExpectAutoSetAndIDArray = stringx.Remove(judgeCaseFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at")
	judgeCaseRowsExpectAutoSetAndID      = strings.Join(judgeCaseRowsExpectAutoSetAndIDArray, ",")
	judgeCaseRowsWithPlaceHolder         = builder.PostgreSqlJoin(stringx.Remove(judgeCaseFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	judgeCaseModel interface {
		Insert(ctx context.Context, data *JudgeCase) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*JudgeCase, error)
		FindOneLock(ctx context.Context, id string) (*JudgeCase, error)
		Update(ctx context.Context, data *JudgeCase) error
		Upsert(ctx context.Context, data *JudgeCase) (sql.Result, error)
		Delete(ctx context.Context, id string) error
	}

	defaultJudgeCaseModel struct {
		conn  sqlx.SqlConn
		table string
	}

	JudgeCase struct {
		Id            string `db:"id"`
		JudgeId       string `db:"judge_id"`
		ProblemDataId string `db:"problem_data_id"`
		Status        int16  `db:"status"`
		TimeUsed      int64  `db:"time_used"`
		MemoryUsed    int64  `db:"memory_used"`
		Reason        string `db:"reason"`
	}
)

func newJudgeCaseModel(conn sqlx.SqlConn) *defaultJudgeCaseModel {
	return &defaultJudgeCaseModel{
		conn:  conn,
		table: `"public"."judge_case"`,
	}
}

func (m *defaultJudgeCaseModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultJudgeCaseModel) FindOne(ctx context.Context, id string) (*JudgeCase, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", judgeCaseRows, m.table)
	var resp JudgeCase
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultJudgeCaseModel) FindOneLock(ctx context.Context, id string) (*JudgeCase, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1 for update", judgeCaseRows, m.table)
	var resp JudgeCase
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultJudgeCaseModel) Insert(ctx context.Context, data *JudgeCase) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7)", m.table, judgeCaseRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.JudgeId, data.ProblemDataId, data.Status, data.TimeUsed, data.MemoryUsed, data.Reason)
	return ret, err
}

func (m *defaultJudgeCaseModel) Update(ctx context.Context, data *JudgeCase) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, judgeCaseRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.JudgeId, data.ProblemDataId, data.Status, data.TimeUsed, data.MemoryUsed, data.Reason)
	return err
}

func (m *defaultJudgeCaseModel) Upsert(ctx context.Context, data *JudgeCase) (sql.Result, error) {
	query := fmt.Sprintf(`
		insert into %s (%s)
		values ($1, $2, $3, $4, $5, $6, $7, $8)
		on conflict (id)
		do update set %s
	`, m.table, judgeCaseRowsExpectAutoSet, judgeCaseRowsWithPlaceHolder)

	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.JudgeId, data.ProblemDataId, data.Status, data.TimeUsed, data.MemoryUsed, data.Reason)
	return ret, err
}

func (m *defaultJudgeCaseModel) tableName() string {
	return m.table
}
