// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/r27153733/fastgozero/core/stores/builder"
	"github.com/r27153733/fastgozero/core/stores/sqlx"
	"github.com/r27153733/fastgozero/core/stringx"

	"github.com/r27153733/ByteMoeOJ/lib/uuid"
)

var (
	usersFieldNames                  = builder.RawFieldNames(&Users{}, true)
	usersRows                        = strings.Join(usersFieldNames, ",")
	usersRowsExpectAutoSet           = strings.Join(stringx.Remove(usersFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	usersRowsExpectAutoSetAndIDArray = stringx.Remove(usersFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at")
	usersRowsExpectAutoSetAndID      = strings.Join(usersRowsExpectAutoSetAndIDArray, ",")
	usersRowsWithPlaceHolder         = builder.PostgreSqlJoin(stringx.Remove(usersFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	usersModel interface {
		Insert(ctx context.Context, data *Users) (sql.Result, error)
		FindOne(ctx context.Context, id uuid.UUID) (*Users, error)
		FindOneLock(ctx context.Context, id uuid.UUID) (*Users, error)
		FindOneByEmail(ctx context.Context, email sql.NullString) (*Users, error)
		DeleteByEmail(ctx context.Context, email sql.NullString) error
		FindOneByUsername(ctx context.Context, username string) (*Users, error)
		DeleteByUsername(ctx context.Context, username string) error
		Update(ctx context.Context, data *Users) error
		Upsert(ctx context.Context, data *Users) (sql.Result, error)
		Delete(ctx context.Context, id uuid.UUID) error
	}

	defaultUsersModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Users struct {
		Id        uuid.UUID      `db:"id"`
		Username  string         `db:"username"`
		Password  string         `db:"password"`
		Name      string         `db:"name"`
		Email     sql.NullString `db:"email"`
		CreatedAt time.Time      `db:"created_at"`
		UpdatedAt time.Time      `db:"updated_at"`
	}
)

func newUsersModel(conn sqlx.SqlConn) *defaultUsersModel {
	return &defaultUsersModel{
		conn:  conn,
		table: `"public"."users"`,
	}
}

func (m *defaultUsersModel) Delete(ctx context.Context, id uuid.UUID) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUsersModel) FindOne(ctx context.Context, id uuid.UUID) (*Users, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", usersRows, m.table)
	var resp Users
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUsersModel) FindOneLock(ctx context.Context, id uuid.UUID) (*Users, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1 for update", usersRows, m.table)
	var resp Users
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUsersModel) FindOneByEmail(ctx context.Context, email sql.NullString) (*Users, error) {
	var resp Users
	query := fmt.Sprintf("select %s from %s where email = $1 limit 1", usersRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, email)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUsersModel) DeleteByEmail(ctx context.Context, email sql.NullString) error {
	query := fmt.Sprintf("delete from %s where email = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, email)
	return err
}

func (m *defaultUsersModel) FindOneByUsername(ctx context.Context, username string) (*Users, error) {
	var resp Users
	query := fmt.Sprintf("select %s from %s where username = $1 limit 1", usersRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, username)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUsersModel) DeleteByUsername(ctx context.Context, username string) error {
	query := fmt.Sprintf("delete from %s where username = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, username)
	return err
}

func (m *defaultUsersModel) Insert(ctx context.Context, data *Users) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5)", m.table, usersRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.Username, data.Password, data.Name, data.Email)
	return ret, err
}

func (m *defaultUsersModel) Update(ctx context.Context, newData *Users) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, usersRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.Username, newData.Password, newData.Name, newData.Email)
	return err
}

func (m *defaultUsersModel) tableName() string {
	return m.table
}

func (m *defaultUsersModel) Upsert(ctx context.Context, data *Users) (sql.Result, error) {
	query := fmt.Sprintf(`
		insert into %s (%s)
		values ($1, $2, $3, $4, $5)
		on conflict (id)
		do update set %s
	`, m.table, usersRowsExpectAutoSet, usersRowsWithPlaceHolder)

	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.Username, data.Password, data.Name, data.Email)
	return ret, err
}
