// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: wasmexecutor.proto

package wasm

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WasmExecutor_Execute_FullMethodName = "/wasm.WasmExecutor/Execute"
)

// WasmExecutorClient is the client API for WasmExecutor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The service definition for executing Wasm modules.
type WasmExecutorClient interface {
	// Executes a Wasm module with the provided inputs and returns the results.
	Execute(ctx context.Context, in *WasmExecutionRequest, opts ...grpc.CallOption) (*WasmExecutionResponse, error)
}

type wasmExecutorClient struct {
	cc grpc.ClientConnInterface
}

func NewWasmExecutorClient(cc grpc.ClientConnInterface) WasmExecutorClient {
	return &wasmExecutorClient{cc}
}

func (c *wasmExecutorClient) Execute(ctx context.Context, in *WasmExecutionRequest, opts ...grpc.CallOption) (*WasmExecutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WasmExecutionResponse)
	err := c.cc.Invoke(ctx, WasmExecutor_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WasmExecutorServer is the server API for WasmExecutor service.
// All implementations must embed UnimplementedWasmExecutorServer
// for forward compatibility.
//
// The service definition for executing Wasm modules.
type WasmExecutorServer interface {
	// Executes a Wasm module with the provided inputs and returns the results.
	Execute(context.Context, *WasmExecutionRequest) (*WasmExecutionResponse, error)
	mustEmbedUnimplementedWasmExecutorServer()
}

// UnimplementedWasmExecutorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWasmExecutorServer struct{}

func (UnimplementedWasmExecutorServer) Execute(context.Context, *WasmExecutionRequest) (*WasmExecutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedWasmExecutorServer) mustEmbedUnimplementedWasmExecutorServer() {}
func (UnimplementedWasmExecutorServer) testEmbeddedByValue()                      {}

// UnsafeWasmExecutorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WasmExecutorServer will
// result in compilation errors.
type UnsafeWasmExecutorServer interface {
	mustEmbedUnimplementedWasmExecutorServer()
}

func RegisterWasmExecutorServer(s grpc.ServiceRegistrar, srv WasmExecutorServer) {
	// If the following call pancis, it indicates UnimplementedWasmExecutorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WasmExecutor_ServiceDesc, srv)
}

func _WasmExecutor_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WasmExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WasmExecutorServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WasmExecutor_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WasmExecutorServer).Execute(ctx, req.(*WasmExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WasmExecutor_ServiceDesc is the grpc.ServiceDesc for WasmExecutor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WasmExecutor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wasm.WasmExecutor",
	HandlerType: (*WasmExecutorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _WasmExecutor_Execute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wasmexecutor.proto",
}
